name: 'Dojo site deployer Action'
author: 'Bas Hopman'
description: 'GitHub Action for Building a CoderDojo Hugo Site and Pushing it to Github Pages'

inputs:
  githubToken:
    description: 'A Github Personal Access Token with Repo permissions'
    required: true

  eventbriteApiKey:
    description: 'API key to get dojo events from Eventbrite'
    required: true

  slackWebhook:
    description: 'Slack webhook to use to send notifications'
    required: true

  cname:
    description: 'The custom domain name for your GH Pages Site'
    required: false

  branch:
    description: 'The branch to push the built site to'
    required: false
    default: 'gh-pages'

  repo:
    description: 'The repo to push the built site to'
    required: false

  hugoVersion:
    description: 'The version of hugo to use'
    required: false

  args:
    description: 'Arguments to pass to Hugo'
    required: false
    default: --gc --minify --cleanDestinationDir

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'upload-cloud'
  color: 'red'