baseURL = "/"
languageCode = "nl-nl"
title = "CoderDojo Nijmegen"

[params]
  mcs = false

[menu]

  [[menu.main]]
    name = "dojos"
    url = "/dojos/"
    weight = -110

  [[menu.main]]
    name = "instructies"
    url = "/onderwerpen/"
    weight = -100

  [[menu.main]]
    name = "team"
    url = "/team/"
    weight = -90

  [[menu.main]]
    name = "meehelpen"
    url = "/meehelpen/"
    weight = -90

  [[menu.main]]
    name = "stichting"
    url = "/stichting/"
    weight = -80

  [[menu.main]]
    name = "zoeken"
    url = "/zoeken/"
    weight = -70

[markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineAnchors = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "github"
  tabWidth = 4

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]
