---
name: Check for dead links
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Install linkchecker
        run: >
          sudo apt update && sudo apt install linkchecker -y
      - name: Check links
        run: >
          linkchecker
          --check-extern
          --no-warnings
          --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36"
          --ignore-url=^mailto:
          --ignore-url=^https://img.evbuc.com
          --ignore-url=^http://localhost
          --ignore-url=^https://www.craiyon.com
          --ignore-url=^https://fonts.googleapis.com
          --ignore-url=^http://leowillems.nl
          https://coderdojo-nijmegen.nl
