name: Check for dead links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Install linkchecker
        run: |
          sudo apt update && sudo apt install linkchecker -y
      - name: Check links
        run: |
          .github/workflows/linkcheck.sh 
