name: Publish Site v2

on:
  push:

jobs:
  publish:
    name: Publish Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo
      - name: Install Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build
        run: PYTHONPATH=src/ python3 -u src/deploy.py